// react19/DragonBall/src/app/layout/Nav.tsx
import { Link } from 'react-router-dom';

export function Nav() {
  return (
    <nav>
      <ul className="navbar d-flex align-items-center">
        <li>
          <a href="https://www.w3schools.com/js/default.asp">w3schools</a>
        </li>
        <li>
          <a href="https://es.javascript.info/js">javascript.info</a>
        </li>
        <li>
          <a href="https://developer.mozilla.org/es/docs/Web/JavaScript">MDN</a>
        </li>

        <li className="ms-auto"></li>

        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/registro">Registro</Link>
        </li>
      </ul>
    </nav>
  );
}

// angular16/DragonBall/src/app/layout/nav/nav.component.ts
import { Component } from '@angular/core';
import { AuthService } from 'src/app/servicios/auth.service';

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.css'],
})
export class NavComponent {
  isLoggedIn = this.authService.isLoggedIn;
  usuario = this.authService.usuario;

  constructor(private authService: AuthService) {}

  logout(): void {
    this.authService.logout();
  }
}

<nav>
  <ul class="navbar d-flex align-items-center">

    <!-- IZQUIERDA (todo lo que ya tienes) -->
    <li><a href="https://www.w3schools.com/js/default.asp">w3schools</a></li>
    <li><a href="https://es.javascript.info/js">javascript.info</a></li>
    <li><a href="https://developer.mozilla.org/es/docs/Web/JavaScript">MDN</a></li>

    <!-- Ejercicios -->
    <li class="dropdown" *ngIf="isLoggedIn()">
      <a href="" (click)="$event.preventDefault()">Ejercicios</a>
      <ul class="dropdown-content">
        <li><a routerLink="/ejercicio01">Ejercicio 01</a></li>
      </ul>
    </li>

    <!-- EMPUJADOR -->
    <li class="ms-auto"></li>

    <!-- DERECHA -->
    <ng-container *ngIf="!isLoggedIn()">
      <li><a routerLink="/login">Login</a></li>
      <li><a routerLink="/registro">Registro</a></li>
    </ng-container>

    <ng-container *ngIf="isLoggedIn()">
      <li class="nav-user">
        👤 {{ usuario()?.nombre }}
      </li>
      <li>
        <a href="" (click)="$event.preventDefault(); logout()">Salir</a>
      </li>
    </ng-container>

  </ul>
</nav>
