// react19/DragonBall/src/app/pages/Registro.tsx
import { useState } from 'react';

export function Registro() {
  const [nombre, setNombre] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  function registrar() {
    console.log(nombre, username, password);
    // NO hay backend real
  }

  return (
    <div className="container-fluid py-3 px-4">
      <h5>Registro</h5>

      <div className="row">
        <div className="col-md-4 mb-2">
          <input
            type="text"
            value={nombre}
            onChange={e => setNombre(e.target.value)}
            className="form-control"
            placeholder="Nombre"
          />
        </div>

        <div className="col-md-4 mb-2">
          <input
            type="text"
            value={username}
            onChange={e => setUsername(e.target.value)}
            className="form-control"
            placeholder="Usuario"
          />
        </div>

        <div className="col-md-4 mb-2">
          <input
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            className="form-control"
            placeholder="Contraseña"
          />
        </div>

        <div className="col-12">
          <button
            type="button"
            className="btn btn-success"
            onClick={registrar}
          >
            Registrarse
          </button>
        </div>
      </div>
    </div>
  );
}

// angular16/DragonBall/src/app/auth/registro/registro.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/servicios/auth.service';

@Component({
  selector: 'app-registro',
  templateUrl: './registro.component.html',
  styleUrls: ['./registro.component.css']
})
export class RegistroComponent {

  nombre = '';
  username = '';
  password = '';

  constructor(
    private authService: AuthService,
    private router: Router
  ) { }

  registrar(): void {
    this.authService.registro(this.nombre, this.username, this.password);
    
    // Redirigir al login después de registro
    this.router.navigate(['/login']);
  }
}

<div class="container-fluid py-3 px-4">
  <h5>Registro</h5>

  <div class="row">
    <div class="col-md-4 mb-2">
      <input
        type="text"
        [(ngModel)]="nombre"
        class="form-control"
        placeholder="Nombre">
    </div>

    <div class="col-md-4 mb-2">
      <input
        type="text"
        [(ngModel)]="username"
        class="form-control"
        placeholder="Usuario">
    </div>

    <div class="col-md-4 mb-2">
      <input
        type="password"
        [(ngModel)]="password"
        class="form-control"
        placeholder="Contraseña">
    </div>

    <div class="col-12">
      <button
        type="button"
        class="btn btn-success"
        (click)="registrar()">
        Registrarse
      </button>
    </div>
  </div>
</div>
