// react19/DragonBall/src/app/layout/Header.tsx
export function Header() {
    return (
        <header className="header d-flex justify-content-between align-items-center">
            <div className="header-content">
                <h3>Ejemplos – FUNDAMENTOS DE JS (ES6)</h3>
                <h4>Desarrollo WEB en entorno cliente</h4>
                <h2>Plantilla</h2>
            </div>

            <div className="header-profile">
                <img src="./assets/user.png" alt="Perfil" />
            </div>
        </header>
    );
}

// angular16/PROYECTO_NAVIDAD/PROYECTO_NAVIDAD/src/app/layout/header/header.component.ts
import { Component } from '@angular/core';
import { AuthService } from 'src/app/servicios/auth.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  constructor(public authService: AuthService){
    
  }
}

<header>
  <div class="header-content">
    <h3>Ejemplos – FUNDAMENTOS DE JS (ES6)</h3>
    <h4>Desarrollo WEB en entorno cliente</h4>
    <h2>Plantilla</h2>
  </div>
  <div class="header-profile">
    <img [src]="authService.usuario()?.imagen || 'assets/user.png'">
  </div>
</header>
