// angular16/PROYECTO_NAVIDAD/PROYECTO_NAVIDAD/src/app/auth/registro/registro.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from 'src/app/servicios/auth.service';

@Component({
  selector: 'app-registro',
  templateUrl: './registro.component.html',
  styleUrls: ['./registro.component.css']
})
export class RegistroComponent {
  nombre: string = '';
  username: string = '';
  password: string = '';
  imagenBase64: string = '';

  constructor(private authService: AuthService,     
              private router: Router) 
  { }

  onFileSelected(event: any) {
    const file: File = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.imagenBase64 = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  }

  rol: string = 'usuario';

  registrar() {
    this.authService.registro(
        this.nombre, 
        this.username, 
        this.password, 
        this.imagenBase64,
        this.rol
    ).subscribe({
        next: (resp: any) => {
            console.log('Registro exitoso', resp);
            this.router.navigate(['/login']);
        },
        error: (err: any) => {
            console.error("Error al registrar:", err);
        }
    });
}
}
<div class="container-fluid py-3 px-4">
    <h5>Registro de Nuevo Usuario</h5>
    <div class="row">
        <div class="col-md-4 mb-3">
            <label class="form-label">Nombre Completo</label>
            <input type="text" [(ngModel)]="nombre" class="form-control" placeholder="Ej: Juan Pérez">
        </div>
        <div class="col-md-4 mb-3">
            <label class="form-label">Nombre de Usuario</label>
            <input type="text" [(ngModel)]="username" class="form-control" placeholder="Usuario">
        </div>
        <div class="col-md-4 mb-3">
            <label class="form-label">Contraseña</label>
            <input type="password" [(ngModel)]="password" class="form-control" placeholder="Contraseña">
        </div>

        <div class="form-group mb-3">
            <label>Rol de usuario:</label>
            <select [(ngModel)]="rol" name="rol" class="form-control">
                <option value="usuario">usuario</option>
                <option value="administrador">administrador</option>
            </select>
        </div>

        <div class="col-md-6 mb-3">
            <label class="form-label">Foto de Perfil</label>
            <input type="file" (change)="onFileSelected($event)" class="form-control" accept="image/*">
        </div>
        
        <div class="col-md-6 mb-3 text-center" *ngIf="imagenBase64">
            <p>Vista previa:</p>
            <img [src]="imagenBase64" class="rounded-circle shadow" style="width: 80px; height: 80px; object-fit: cover;">
        </div>

        <div class="col-12 mt-2">
            <button type="button" class="btn btn-success" (click)="registrar()" [disabled]="!nombre || !username || !password">
                Registrarse
            </button>
        </div>
    </div>
</div>

// react19/DragonBall/src/app/pages/Registro.tsx
import { useState } from 'react';

export function Registro() {
  const [nombre, setNombre] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');

  function registrar() {
    console.log(nombre, username, password);
    // NO hay backend real
  }

  return (
    <div className="container-fluid py-3 px-4">
      <h5>Registro</h5>

      <div className="row">
        <div className="col-md-4 mb-2">
          <input
            type="text"
            value={nombre}
            onChange={e => setNombre(e.target.value)}
            className="form-control"
            placeholder="Nombre"
          />
        </div>

        <div className="col-md-4 mb-2">
          <input
            type="text"
            value={username}
            onChange={e => setUsername(e.target.value)}
            className="form-control"
            placeholder="Usuario"
          />
        </div>

        <div className="col-md-4 mb-2">
          <input
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            className="form-control"
            placeholder="Contraseña"
          />
        </div>

        <div className="col-12">
          <button
            type="button"
            className="btn btn-success"
            onClick={registrar}
          >
            Registrarse
          </button>
        </div>
      </div>
    </div>
  );
}
