// react19/DragonBall/src/app/pages/Login.tsx
import { useState } from 'react';

export function Login() {
  const [usuario, setUsuario] = useState('');
  const [password, setPassword] = useState('');
  const [loginIncorrecto, setLoginIncorrecto] = useState(false);

  function hacerLogin() {
    // NO implementamos auth real
    // Solo simulamos el flujo
    console.log(usuario, password);

    if (usuario && password) {
      setLoginIncorrecto(false);
    } else {
      setLoginIncorrecto(true);
    }
  }

  return (
    <div className="container-fluid py-3 px-4">
      <h5>Login</h5>

      <div className="row">
        <div className="col-md-6 mb-2">
          <input
            type="text"
            value={usuario}
            onChange={e => setUsuario(e.target.value)}
            className="form-control"
            placeholder="Usuario"
          />
        </div>

        <div className="col-md-6 mb-2">
          <input
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            className="form-control"
            placeholder="Contraseña"
          />
        </div>

        <div className="col-12">
          <button
            type="button"
            className="btn btn-primary"
            onClick={hacerLogin}
          >
            Entrar
          </button>
        </div>

        {loginIncorrecto && (
          <div className="col-12 mt-2 text-danger">
            Login incorrecto
          </div>
        )}
      </div>
    </div>
  );
}

// angular16/PROYECTO_NAVIDAD/PROYECTO_NAVIDAD/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from 'src/app/servicios/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  usuario: string = '';
  password: string = '';
  loginIncorrecto: boolean = false;

  constructor(
    private authService: AuthService,
    private router: Router,
    private route: ActivatedRoute
  
  ) { }

  hacerLogin(): void {
    this.authService.login(this.usuario, this.password);    
    if (this.authService.isLoggedIn()) {
      const returnUrl = this.route.snapshot.queryParams['returnUrl'] || '/inicio';
      console.log(returnUrl);
      this.router.navigate([returnUrl]);
    } else {
      this.loginIncorrecto = true;
    }
  }
}

<div class="container-fluid py-3 px-4">
    <h5>Login</h5>
    <div class="row">
        <div class="col-md-6 mb-2">
            <input type="text" [(ngModel)]="usuario" class="form-control" placeholder="Usuario">
        </div>
        <div class="col-md-6 mb-2">
            <input type="password" [(ngModel)]="password" class="form-control" placeholder="Contraseña">
        </div>
        <div class="col-12">
            <button type="button" class="btn btn-primary" (click)="hacerLogin()">
                Entrar
            </button>
        </div>
    </div>
</div>
